# Generated by Django 4.0 on 2023-01-15 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='sex',
        ),
        migrations.AddField(
            model_name='candidates',
            name='sex',
            field=models.ManyToManyField(to='TestApp.Technology'),
        ),
    ]
