# Generated by Django 4.0 on 2023-01-15 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0002_remove_candidates_sex_candidates_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='updated_at',
        ),
    ]
