# Generated by Django 4.0 on 2023-01-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0003_remove_technology_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='technology',
            field=models.ManyToManyField(to='TestApp.Technology'),
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='sex',
        ),
        migrations.AddField(
            model_name='candidates',
            name='sex',
            field=models.CharField(default=1, max_length=250, verbose_name='Sex'),
            preserve_default=False,
        ),
    ]
