# Generated by Django 4.0 on 2023-01-15 04:19

import TestApp.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0004_candidates_technology_remove_candidates_sex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('year', models.IntegerField(validators=[TestApp.utils.validate_only_numbers], verbose_name='Years of experience')),
            ],
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='technology',
        ),
        migrations.DeleteModel(
            name='YearExperience',
        ),
        migrations.AddField(
            model_name='technologycandidate',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.candidates', verbose_name='Candidate'),
        ),
        migrations.AddField(
            model_name='technologycandidate',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestApp.technology', verbose_name='Technology'),
        ),
    ]
