# Generated by Django 4.0 on 2023-01-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0005_technologycandidate_remove_candidates_technology_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologycandidate',
            options={'ordering': ['-year']},
        ),
    ]
